version: 2.1

commands:
  npm-install:
    parameters:
    steps:
      - restore_cache:
          name: Restore NPM Cache
          keys:
            - npm-install-cache-{{ .Environment.CACHE_TRIGGER_VERSION }}-{{ arch }}-{{ checksum "package-lock.json" }}
            - npm-install-cache-{{ .Environment.CACHE_TRIGGER_VERSION }}-{{ arch }}-
      - run:
          name: NPM Install
          command: |
            echo "Node version: $(node --version)"
            npm ci --prefer-offline --no-audit
      - save_cache:
          name: Save NPM Cache
          key: npm-install-cache-{{ .Environment.CACHE_TRIGGER_VERSION }}-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - src/i18n-cache
            - ~/.local/share/pnpm/store/v3
            - ~/Library/pnpm/store/v3
  npm-install-full:
    parameters:
      additional-flags:
        type: string
        default: ""
    steps:
      - restore_cache:
          name: Restore NPM Cache
          keys:
            - npm-install-full-cache-{{ .Environment.CACHE_TRIGGER_VERSION }}-{{ arch }}-{{ checksum "gutenberg/package-lock.json" }}
            - npm-install-full-cache-{{ .Environment.CACHE_TRIGGER_VERSION }}-{{ arch }}-
      - run:
          name: NPM Install Full
          command: |
            echo "Node version: $(node --version)"
            npm install --no-audit
      - save_cache:
          name: Save NPM Cache
          key: npm-install-full-cache-{{ .Environment.CACHE_TRIGGER_VERSION }}-{{ arch }}-{{ checksum "gutenberg/package-lock.json" }}
          paths:
            - ~/.npm
            - src/i18n-cache
            - ~/.local/share/pnpm/store/v3
            - ~/Library/pnpm/store/v3
  npm-install-e2e-tests:
    parameters:
    steps:
      - restore_cache:
          name: Restore NPM Cache
          keys:
            - npm-install-cache-{{ .Environment.CACHE_TRIGGER_VERSION }}-{{ arch }}-{{ checksum "package-lock.json" }}
            - npm-install-cache-{{ .Environment.CACHE_TRIGGER_VERSION }}-{{ arch }}-
      - run:
          name: NPM Install (E2E Tests)
          command: |
            echo "Node version: $(node --version)"
            npm ci --prefer-offline --no-audit --ignore-scripts
            npm ci --prefix gutenberg --prefer-offline --no-audit
  checkout-shallow:
    steps:
      - run:
          name: Checkout (Shallow)
          command: |
            #!/bin/sh
            set -e

            # Workaround old docker images with incorrect $HOME
            # check https://github.com/docker/docker/issues/2968 for details
            if [ "${HOME}" = "/" ]
            then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi

            SSH_CONFIG_DIR="$HOME/.ssh"
            echo "Using SSH Config Dir '$SSH_CONFIG_DIR'"
            git --version 

            mkdir -p "$SSH_CONFIG_DIR"
            chmod 0700 "$SSH_CONFIG_DIR"

            printf "%s" 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
            bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
            ' >> "$SSH_CONFIG_DIR/known_hosts"
            chmod 0600 "$SSH_CONFIG_DIR/known_hosts"

            export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile='$SSH_CONFIG_DIR/known_hosts'"

            # use git+ssh instead of https
            git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
            git config --global gc.auto 0 || true

            if [ -e "$HOME/project/.git" ] ; then
              echo 'Fetching into existing repository'
              existing_repo='true'
              cd "$HOME/project"
              git remote set-url origin "$CIRCLE_REPOSITORY_URL" || true
            else
              echo 'Cloning git repository'
              existing_repo='false'
              mkdir -p "$HOME/project"
              cd "$HOME/project"
              git clone --depth 1 --no-checkout "$CIRCLE_REPOSITORY_URL" .
            fi

            echo 'Fetching from remote repository'
            if [ -n "$CIRCLE_TAG" ]; then
              git fetch --depth 1 --force --tags origin "refs/tags/$CIRCLE_TAG"
            else
              git fetch --depth 1 --force origin "$CIRCLE_SHA1"
            fi

            if [ -n "$CIRCLE_TAG" ]; then
              echo 'Checking out tag'
              git checkout --force "$CIRCLE_TAG"
              git reset --hard "$CIRCLE_SHA1"
            else
              echo 'Checking out branch'
              git checkout --force -B "$CIRCLE_BRANCH" "$CIRCLE_SHA1"
              git --no-pager log --no-color -n 1 --format='HEAD is now at %h %s'
            fi
  checkout-submodules:
    steps:
      - run:
          name: Checkout Submodules
          command: git submodule update --init --recursive --depth 1
  add-jest-reporter-dir:
      steps:
        - run:
            name: Create reports directory
            command: mkdir reports && mkdir reports/test-results
  add-jest-snapshot-dir:
      steps:
        - run:
            name: Create snapshots directory
            command: mkdir __device-tests__/image-snapshots/diff
  install-node-version:
    steps:
      - run:
          name: Install newer nvm
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            if [ -z "${NVM_DIR}" ] ; then
              echo 'Default NVM_DIR to .nvm in home'
              echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            fi
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Install node version specified in .nvmrc using nvm
          command: |
            nvm install
            # Set the installed version as the default one
            nvm alias default $(nvm current)
            # Enforce to use the default version in the rest of workflow
            echo 'nvm use default' >> $BASH_ENV

parameters:
  android-docker-image:
    type: string
    # Hash points to previous version with node 12. When everything works with node 14 it can be removed
    default: "circleci/android:api-29-node@sha256:71d61d6c21b29948d57120f476a83cc322a280979bce355c5a0ad771293ca380"
  linux-machine-image:
    type: string
    # Latest supported ubuntu image from https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
    default: "ubuntu-2004:2022.10.1"

jobs:
  checks:
    parameters:
      platform:
        type: string
        default: ""
      check-tests:
        type: boolean
        default: false
      check-correctness:
        type: boolean
        default: false
    machine:
      image: << pipeline.parameters.linux-machine-image >>
    steps:
      - checkout-shallow
      - checkout-submodules
      - install-node-version
      - when:
          condition: <<parameters.check-correctness>>
          steps:
            - npm-install-full
      - unless:
          condition: <<parameters.check-correctness>>
          steps:
            - npm-install
      - add-jest-reporter-dir
      - run:
          name: Set Environment Variables
          command: |
            echo 'export CHECK_CORRECTNESS=<<parameters.check-correctness>>' >> $BASH_ENV
            echo 'export CHECK_TESTS=<<parameters.check-tests>>' >> $BASH_ENV
            echo 'export TEST_RN_PLATFORM=<<parameters.platform>>' >> $BASH_ENV
      - run:
          name: Run Checks
          command: bin/ci-checks-js.sh
          environment:
            JEST_JUNIT_OUTPUT_FILE: "reports/test-results/android-test-results.xml"
      - store_test_results:
          path: ./reports/test-results
  android-build:
    machine:
      image: << pipeline.parameters.linux-machine-image >>
    steps:
      - checkout-shallow
      - checkout-submodules
      - install-node-version
      - run: node -v
      - npm-install
      - run: npm run test:e2e:bundle:android
      - run:
          name: Build apk
          command: |
            docker run --rm -it \
            --volume $(pwd):/home/circleci/project \
            --workdir /home/circleci/project \
            --env JAVA_OPTS='-Xms512m -Xmx2g' \
            --env GRADLE_OPTS='-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"' \
            << pipeline.parameters.android-docker-image >> \
            /bin/bash -c "sudo chown -R circleci:circleci . && npm run core test:e2e:build-app:android"
      - run:
          name: Upload apk to sauce labs
          command: |
            source bin/sauce-pre-upload.sh
            curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
            --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
            --form 'payload=@"./gutenberg/packages/react-native-editor/android/app/build/outputs/apk/debug/app-debug.apk"' \
            --form "name=Gutenberg-$SAUCE_FILENAME.apk" \
            --form 'description="Gutenberg"'
  android-device-checks:
    parameters:
      post-to-slack:
        description: Post to Slack when tests fail. SLACK_WEBHOOK ENV variable must be set.
        type: boolean
        default: false
      is-canary:
        type: string
        default: ""
    machine:
      image: << pipeline.parameters.linux-machine-image >>
    steps:
      - checkout-shallow
      - checkout-submodules
      - install-node-version
      - run: node -v
      - npm-install-e2e-tests
      - add-jest-snapshot-dir
      - run: mkdir /home/circleci/test-results
      - run:
          name: Run Device Tests
          command: npm run device-tests<<parameters.is-canary>>
          no_output_timeout: 1200
          environment:
            TEST_RN_PLATFORM: android
            TEST_ENV: sauce
            JEST_JUNIT_OUTPUT_FILE: "/home/circleci/test-results/android-test-results.xml"
      - store_test_results:
          path: /home/circleci/test-results
  android-native-unit-tests:
    parameters:
      post-to-slack:
        description: Post to Slack when tests fail. SLACK_WEBHOOK ENV variable must be set.
        type: boolean
        default: false
    docker:
    - image: << pipeline.parameters.android-docker-image >>
    steps:
      - checkout-shallow
      - checkout-submodules
      - install-node-version
      - npm-install
      - run:
          name: Run Android native-editor unit tests
          command: cd gutenberg/packages/react-native-editor/android && ./gradlew testDebug
      - run:
          name: Run Android native-bridge unit tests
          command: cd gutenberg/packages/react-native-bridge/android && ./gradlew test
  ios-build:
    macos:
      xcode: "13.4.1"
    steps:
    - checkout-shallow
    - checkout-submodules
    - install-node-version
    - npm-install
    - run:
        name: Set Environment Variables
        command: |
          echo 'export TEST_RN_PLATFORM=ios' >> $BASH_ENV
          echo 'export TEST_ENV=sauce' >> $BASH_ENV
    - run:
        name: Prepare build cache key
        command: find gutenberg/package-lock.json gutenberg/packages/react-native-editor/ios gutenberg/packages/react-native-aztec/ios gutenberg/packages/react-native-bridge/ios -type f -print0 | sort -z | xargs -0 shasum | tee ios-checksums.txt
    - restore_cache:
        name: Restore Build Cache
        keys:
          - ios-build-cache-{{ checksum "ios-checksums.txt" }}
    - restore_cache:
        name: Restore Dependencies Cache
        keys:
        - dependencies-v6-{{ checksum "gutenberg/packages/react-native-editor/ios/Gemfile.lock" }}-{{ checksum "gutenberg/packages/react-native-editor/ios/Podfile.lock" }}-{{ checksum "gutenberg/package-lock.json" }}
        - dependencies-v6-{{ checksum "gutenberg/packages/react-native-editor/ios/Gemfile.lock" }}-{{ checksum "gutenberg/packages/react-native-editor/ios/Podfile.lock" }}
        - dependencies-v6-{{ checksum "gutenberg/packages/react-native-editor/ios/Gemfile.lock" }}
        - dependencies-v6-
    - run:
        name: Build (if needed)
        command: test -e gutenberg/packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app || npm run core test:e2e:build-app:ios
    - save_cache:
        name: Save Dependencies Cache
        key: dependencies-v6-{{ checksum "gutenberg/packages/react-native-editor/ios/Gemfile.lock" }}-{{ checksum "gutenberg/packages/react-native-editor/ios/Podfile.lock" }}-{{ checksum "gutenberg/package-lock.json" }}
        paths:
        - gutenberg/packages/react-native-editor/ios/Pods
        - ~/Library/Caches/CocoaPods
        - ~/.cocoapods/repos/trunk
        - gutenberg/packages/react-native-editor/ios/vendor
    - run:
        name: Bundle iOS
        command: npm run test:e2e:bundle:ios
    - run:
        name: Generate .app file for testing
        command: WORK_DIR=$(pwd) && cd ./gutenberg/packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator && zip -r $WORK_DIR/gutenberg/packages/react-native-editor/ios/GutenbergDemo.app.zip GutenbergDemo.app
    - run:
        name: Upload .app to sauce labs
        command: |
          source bin/sauce-pre-upload.sh
          curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
          --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
          --form 'payload=@"./gutenberg/packages/react-native-editor/ios/GutenbergDemo.app.zip"' \
          --form "name=Gutenberg-$SAUCE_FILENAME.app.zip" \
          --form 'description="Gutenberg"'
    - run:
        name: Prepare build cache
        command: rm gutenberg/packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app/main.jsbundle
    - save_cache:
        name: Save Build Cache
        key: ios-build-cache-{{ checksum "ios-checksums.txt" }}
        paths:
          - gutenberg/packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app
  ios-device-checks:
    parameters:
      post-to-slack:
        description: Post to Slack when tests fail. SLACK_WEBHOOK ENV variable must be set.
        type: boolean
        default: false
      is-canary:
        type: string
        default: ""
      is-ipad:
        type: string
        default: ""
    macos:
      xcode: "13.4.1"
    steps:
    - checkout-shallow
    - checkout-submodules
    - install-node-version
    - npm-install-e2e-tests
    - add-jest-reporter-dir
    - add-jest-snapshot-dir
    - run:
        name: Set Environment Variables
        command: |
          echo 'export TEST_RN_PLATFORM=ios' >> $BASH_ENV
          echo 'export TEST_ENV=sauce' >> $BASH_ENV
    - run:
        name: Run Device Tests
        command: |
          npm run device-tests<<parameters.is-canary>><<parameters.is-ipad>>
        no_output_timeout: 1200
        environment:
          JEST_JUNIT_OUTPUT_FILE: "reports/test-results/ios-test-results.xml"
    - store_test_results:
        path: ./reports/test-results

workflows:
  gutenberg-mobile:
    jobs:
      - checks:
          name: Check Correctness
          check-correctness: true
      - checks:
          name: Test iOS
          platform: ios
          check-tests: true
      - checks:
          name: Test Android
          platform: android
          check-tests: true
      - ios-build:
          name: iOS Build
      - android-build:
          name: Android Build
      - ios-device-checks:
          name: Test iOS on Device - Canaries
          is-canary: "-canary"
          requires: [ "Test iOS", "iOS Build" ]
      - android-device-checks:
          name: Test Android on Device - Canaries
          is-canary: "-canary"
          requires: [ "Test Android", "Android Native Unit Tests", "Android Build" ]
      - android-native-unit-tests:
          name: Android Native Unit Tests
      # For regular branches the full test suite is optional.
      - Optional UI Tests:
          type: approval
          filters:
            branches:
              ignore:
                - trunk
                - /^dependabot/submodules/.*/
                - /^release.*/
      - ios-device-checks:
          name: Test iOS on Device - Full (Manually triggered)
          requires: [ "Optional UI Tests", "Test iOS", "iOS Build" ]
          filters:
            branches:
              ignore:
                - trunk
                - /^dependabot/submodules/.*/
                - /^release.*/
      - ios-device-checks:
          name: Test iOS on Device - iPad (Manually triggered)
          is-ipad: "-ipad"
          requires: [ "Optional UI Tests", "Test iOS", "iOS Build" ]
          filters:
            branches:
              ignore:
                - trunk
                - /^dependabot/submodules/.*/
                - /^release.*/
      - android-device-checks:
          name: Test Android on Device - Full (Manually triggered)
          requires: [ "Optional UI Tests", "Test Android", "Android Native Unit Tests", "Android Build" ]
          filters:
            branches:
              ignore:
                - trunk
                - /^dependabot/submodules/.*/
                - /^release.*/
      # For `trunk`, Dependabot, and release branches we always run the full test suite.
      - ios-device-checks:
          name: Test iOS on Device - Full
          post-to-slack: true
          requires: [ "Test iOS", "iOS Build" ]
          filters:
            branches:
              only:
                - trunk
                - /^dependabot/submodules/.*/
                - /^release.*/
      - ios-device-checks:
          name: Test iOS on Device - iPad
          is-ipad: "-ipad"
          post-to-slack: true
          requires: [ "Test iOS", "iOS Build" ]
          filters:
            branches:
              only:
                - trunk
                - /^dependabot/submodules/.*/
                - /^release.*/
      - android-device-checks:
          name: Test Android on Device - Full
          post-to-slack: true
          requires: [ "Test Android", "Android Native Unit Tests", "Android Build" ]
          filters:
            branches:
              only: 
                - trunk
                - /^dependabot/submodules/.*/
                - /^release.*/