version: 2.1

orbs:
  android: wordpress-mobile/android@dev:add/android-bintray-publishing
  slack: circleci/slack@3.4.2

commands:
  npm-install:
    steps:
      - restore_cache:
          name: Restore NPM Cache
          keys:
            - npm-i18n-v4-cache-v{{ .Environment.CACHE_TRIGGER_VERSION }}-job-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
      - run:
          name: NPM Install
          command: npm ci --prefer-offline
      - save_cache:
          name: Save NPM Cache
          key: npm-i18n-v4-cache-v{{ .Environment.CACHE_TRIGGER_VERSION }}-job-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - i18n-cache/data
  npm-install-full:
    steps:
      - restore_cache:
          name: Restore NPM Cache
          keys:
            - npm-i18n-v4-cache-v{{ .Environment.CACHE_TRIGGER_VERSION }}-job-{{ .Environment.CIRCLE_JOB }}-{{ checksum "gutenberg/package-lock.json" }}
      - run:
          name: NPM Install Full
          command: npm install
      - save_cache:
          name: Save NPM Cache
          key: npm-i18n-v4-cache-v{{ .Environment.CACHE_TRIGGER_VERSION }}-job-{{ .Environment.CIRCLE_JOB }}-{{ checksum "gutenberg/package-lock.json" }}
          paths:
            - ~/.npm
            - i18n-cache/data
  checkout-submodules:
    steps:
      - run:
          name: Checkout Submodules
          command: git submodule update --init --recursive
  add-jest-reporter-dir:
      steps:
        - run:
            name: Create reports directory
            command: mkdir reports && mkdir reports/test-results

parameters:
  android-docker-image:
    type: string
    # Hash points to previous version with node 12. When everything works with node 14 it can be removed
    default: "circleci/android:api-29-node@sha256:71d61d6c21b29948d57120f476a83cc322a280979bce355c5a0ad771293ca380" 
  linux-machine-image:
    type: string
    # Latest supported ubuntu image from https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
    default: "ubuntu-2004:202010-01" 

jobs:
  checks:
    parameters:
      platform:
        type: string
        default: ""
      check-tests:
        type: boolean
        default: false
      check-correctness:
        type: boolean
        default: false
    machine:
      image: << pipeline.parameters.linux-machine-image >>
    steps:
      - checkout
      - checkout-submodules
      - run:
          name: Install newer nvm
          command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      - run:
          name: Install newer node using nvm
          command: |
            cd gutenberg
            nvm install --latest-npm
      - when:
          condition: <<parameters.check-correctness>>
          steps:
            - npm-install-full
      - unless:
          condition: <<parameters.check-correctness>>
          steps:
            - npm-install
      - add-jest-reporter-dir
      - run:
          name: Set Environment Variables
          command: |
            echo 'export CHECK_CORRECTNESS=<<parameters.check-correctness>>' >> $BASH_ENV
            echo 'export CHECK_TESTS=<<parameters.check-tests>>' >> $BASH_ENV
            echo 'export TEST_RN_PLATFORM=<<parameters.platform>>' >> $BASH_ENV
      - run:
          name: Run Checks
          command: bin/ci-checks-js.sh
          environment:
            JEST_JUNIT_OUTPUT: "reports/test-results/android-test-results.xml"
      - store_test_results:
          path: ./reports/test-results
  android-device-checks:
    parameters:
      post-to-slack:
        description: Post to Slack when tests fail. SLACK_WEBHOOK ENV variable must be set.
        type: boolean
        default: false
      is-canary:
        type: string
        default: ""
    machine:
      image: << pipeline.parameters.linux-machine-image >>
    steps:
      - checkout
      - checkout-submodules
      - run: node -v
      - run: npm install -g yarn
      - npm-install
      - run: npm run test:e2e:bundle:android
      - run:
          name: Build apk
          command: |
            docker run --rm -it \
            --volume $(pwd):/home/circleci/project \
            --workdir /home/circleci/project \
            --env JAVA_OPTS='-Xms512m -Xmx2g' \
            --env GRADLE_OPTS='-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"' \
            << pipeline.parameters.android-docker-image >> \
            /bin/bash -c "sudo chown -R circleci:circleci . && npm run core test:e2e:build-app:android"
      - run:
          name: Upload apk to sauce labs
          command: |
            source bin/sauce-pre-upload.sh
            curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" -X POST -H "Content-Type: application/octet-stream" https://saucelabs.com/rest/v1/storage/automattic/Gutenberg-$SAUCE_FILENAME.apk?overwrite=true --data-binary @./gutenberg/packages/react-native-editor/android/app/build/outputs/apk/debug/app-debug.apk
      - run: mkdir /home/circleci/test-results
      - run:
          name: Run Device Tests
          command: npm run device-tests<<parameters.is-canary>>
          no_output_timeout: 1200
          environment:
            TEST_RN_PLATFORM: android
            TEST_ENV: sauce
            JEST_JUNIT_OUTPUT: "/home/circleci/test-results/android-test-results.xml"
      - store_test_results:
          path: /home/circleci/test-results
      - when:
          condition: << parameters.post-to-slack >>
          steps:
            - slack/status:
                fail_only: true
                include_job_number_field: false
                include_project_field: false
                failure_message: ':red_circle: Scheduled tests failed on Android device!'
  android-native-unit-tests:
    parameters:
      post-to-slack:
        description: Post to Slack when tests fail. SLACK_WEBHOOK ENV variable must be set.
        type: boolean
        default: false
    docker:
    - image: << pipeline.parameters.android-docker-image >>
    steps:
      - checkout
      - checkout-submodules
      - npm-install
      - run:
          name: Run Android native unit tests
          command: cd gutenberg/packages/react-native-editor/android && ./gradlew testDebug
  ios-device-checks:
    parameters:
      post-to-slack:
        description: Post to Slack when tests fail. SLACK_WEBHOOK ENV variable must be set.
        type: boolean
        default: false
      is-canary:
        type: string
        default: ""
    macos:
      xcode: "12.0.0"
    steps:
    - checkout
    - checkout-submodules
    - npm-install
    - add-jest-reporter-dir
    - run:
        name: Set Environment Variables
        command: |
          echo 'export TEST_RN_PLATFORM=ios' >> $BASH_ENV
          echo 'export TEST_ENV=sauce' >> $BASH_ENV
    - run:
        name: Prepare build cache key
        command: find gutenberg/package-lock.json gutenberg/packages/react-native-editor/ios gutenberg/packages/react-native-aztec/ios gutenberg/packages/react-native-bridge/ios -type f -print0 | sort -z | xargs -0 shasum | tee ios-checksums.txt
    - restore_cache:
        name: Restore Build Cache
        keys:
          - ios-build-cache-{{ checksum "ios-checksums.txt" }}
    - restore_cache:
        name: Restore Dependencies Cache
        keys:
        - dependencies-v4-{{ checksum "gutenberg/packages/react-native-editor/ios/Gemfile.lock" }}-{{ checksum "gutenberg/packages/react-native-editor/ios/Podfile.lock" }}-{{ checksum "gutenberg/package-lock.json" }}
        - dependencies-v4-{{ checksum "gutenberg/packages/react-native-editor/ios/Gemfile.lock" }}-{{ checksum "gutenberg/packages/react-native-editor/ios/Podfile.lock" }}
        - dependencies-v4-{{ checksum "gutenberg/packages/react-native-editor/ios/Gemfile.lock" }}
        - dependencies-v4-
    - run:
        name: Build (if needed)
        command: test -e gutenberg/packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app || npm run core test:e2e:build-app:ios
    - save_cache:
        name: Save Dependencies Cache
        key: dependencies-v4-{{ checksum "gutenberg/packages/react-native-editor/ios/Gemfile.lock" }}-{{ checksum "gutenberg/packages/react-native-editor/ios/Podfile.lock" }}-{{ checksum "gutenberg/package-lock.json" }}
        paths:
        - gutenberg/packages/react-native-editor/ios/Pods
        - ~/Library/Caches/CocoaPods
        - ~/.cocoapods/repos/trunk
        - gutenberg/packages/react-native-editor/ios/vendor
    - run:
        name: Bundle iOS
        command: npm run test:e2e:bundle:ios
    - run:
        name: Generate .app file for testing
        command: WORK_DIR=$(pwd) && cd ./gutenberg/packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator && zip -r $WORK_DIR/gutenberg/packages/react-native-editor/ios/GutenbergDemo.app.zip GutenbergDemo.app
    - run:
        name: Upload .app to sauce labs
        command: |
          source bin/sauce-pre-upload.sh
          HOMEBREW_NO_AUTO_UPDATE=1 brew install curl
          /usr/local/opt/curl/bin/curl --version
          /usr/local/opt/curl/bin/curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" -X POST -H "Content-Type: application/octet-stream" https://saucelabs.com/rest/v1/storage/automattic/Gutenberg-$SAUCE_FILENAME.app.zip?overwrite=true --data-binary @./gutenberg/packages/react-native-editor/ios/GutenbergDemo.app.zip
    - run:
        name: Run Device Tests
        command: |
          npm run device-tests<<parameters.is-canary>>
        no_output_timeout: 1200
        environment:
          JEST_JUNIT_OUTPUT: "reports/test-results/ios-test-results.xml"
    - store_test_results:
        path: ./reports/test-results
    - run:
        name: Prepare build cache
        command: rm gutenberg/packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app/main.jsbundle
    - save_cache:
        name: Save Build Cache
        key: ios-build-cache-{{ checksum "ios-checksums.txt" }}
        paths:
          - gutenberg/packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app
    - when:
          condition: << parameters.post-to-slack >>
          steps:
            - slack/status:
                fail_only: true
                include_job_number_field: false
                include_project_field: false
                failure_message: ':red_circle: Scheduled tests failed on iOS device!'

  android-bintray-publish:
    # parameters:
    #   post-to-slack:
    #     description: Post to Slack when tests fail. SLACK_WEBHOOK ENV variable must be set.
    #     type: boolean
    #     default: false
    docker:
    - image: << pipeline.parameters.android-docker-image >>
    steps:
      - checkout
      - checkout-submodules
      - npm-install
      # I'd expect this to work, but it fails with:
      #
      # ./gradlew: No such file or directory
      #
      # https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/9718/workflows/a4652147-ed0d-4fdb-b910-f045c06b89dd/jobs/51517
      # - run:
      #     name: cd to the React Native Android Bridge folder
      #     command: cd gutenberg/packages/react-native-editor/android
      # - android/publish-to-bintray
      - run:
          name: Upload Android bridge to Bintray
          command: |
            cd gutenberg/packages/react-native-editor/android

            # Configure memory for Gradle task, it needs more than the default
            #
            # See discussion at:
            # https://github.com/wordpress-mobile/gutenberg-mobile/issues/2972
            echo "org.gradle.jvmargs=-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError" >> gradle.properties

            cat gradle.properties

            # Use a different versioning style for builds from PRs to allow
            # developers to iterate faster.
            #
            # All those dev builds will be deleted once the PR is merged by
            # https://github.com/Automattic/bintray-garbage-collector/
            #
            # If $PREFIX is not set, that is, if we're not on a PR but a merge
            # commit on develop or trunk, the version will be the value from
            # the source code.
            branch=$CIRCLE_BRANCH
            if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
              # Making the assumption that $CIRCLE_SHA1 will always be
              # available.
              PREFIX="$PR_NUMBER-$CIRCLE_SHA1"
            elif [[ "$branch" != "trunk" && "$branch" != "develop" ]]; then
              # This happens on the first push of a new branch, when there
              # isn't a PR open for it yet.
              echo "Running on a feature branch with no open PR: skipping Bintray upload"
              exit 0
            fi

            # Because we have Gradle's configure-on-demand option set to true,
            # simply calling `bintrayUpload` won't generate the AAR and POM;
            # we need to explicitly do it here.
            #
            # See
            # https://github.com/wordpress-mobile/circleci-orbs/blob/82f9821130890756e85277486ca0dde6cae25431/src/android/orb.yml#L19),
            #
            # - `assembleRelease` builds the AAR
            # - `generatePomFileForUtilsPublicationPublication` builds the POM
            # - `bintrayUpload` uploads both, using the version value set via
            #   `-PbintrayVersion`
            #
            # Worth noting that the Bintray plugin mentions the necessity for
            # some workarounds to generate the POM under certain circumstances,
            # although none of them apply to our current usage.
            #
            # See:
            # https://github.com/bintray/gradle-bintray-plugin/tree/67718c3a65b64dbfe7534a82a178da2c57153a5d#maven-publications
            #
            # See also the description and comments in this PR:
            # https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/39
            #
            # Calling `assembleRelease` in the same `./gradlew` invocation as
            # the other tasks results in the AAR not being found, so we'll call
            # that alone first.
            #
            # See:
            # https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Utils-Android/165/workflows/b0cb954f-315d-4c54-99a7-c36d11eec5c8/jobs/342
            ./gradlew --stacktrace --debug assembleRelease

            ./gradlew --stacktrace \
              generatePomFileForGutenbergMobilePublicationPublication \
              bintrayUpload \
              -PbintrayVersion=$PREFIX

workflows:
  bintray-publish-test:
    jobs:
      - android-bintray-publish
  gutenberg-mobile:
    jobs:
      - checks:
          name: Check Correctness
          check-correctness: true
      - checks:
          name: Test iOS
          platform: ios
          check-tests: true
      - checks:
          name: Test Android
          platform: android
          check-tests: true
      - ios-device-checks:
          name: Test iOS on Device - Canaries
          is-canary: "-canary"
      - android-device-checks:
          name: Test Android on Device - Canaries
          is-canary: "-canary"
      - Optional UI Tests:
          type: approval
          filters:
            branches:
              ignore:
                - develop
                - /^dependabot/submodules/.*/
      - ios-device-checks:
          name: Test iOS on Device - Full
          requires: [ "Optional UI Tests" ]
      - android-device-checks:
          name: Test Android on Device - Full
          requires: [ "Optional UI Tests" ]
      - android-native-unit-tests:
          name: Android Native Unit Tests
      - ios-device-checks:
          name: Test iOS on Device - Full (Submodule Update)
          post-to-slack: true
          filters:
            branches:
              only: /^dependabot/submodules/.*/
      - android-device-checks:
          name: Test Android on Device - Full (Submodule Update)
          post-to-slack: true
          filters:
            branches:
              only: /^dependabot/submodules/.*/

  ui-tests-full-scheduled:
    jobs:
      - ios-device-checks:
          name: Test iOS on Device - Scheduled
          post-to-slack: true
      - android-device-checks:
          name: Test Android on Device - Scheduled
          post-to-slack: true
    triggers:
      - schedule:
          cron: '1 1,13 * * *'
          filters:
            branches:
              only: develop
